version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file spamFiltering.yaml --s3-bucket spamfilterpipeline --output-template-file outputsamtemplate.yml
artifacts:
  type: zip
  files:
    - spamFiltering.yaml
    - outputsamtemplate.yml