AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Spam Filtering
Resources:
  spamFilter:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: spam-filter
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./spam-filter
      Description: "Lambda function for CD Demo"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::269578278636:role/admin-lambda-role"
      Environment:
        Variables:
          REGION: us-east-1
  emailBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: email-bucket-v3
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:Put'
            Function: !GetAtt 
              - spamFilter
              - Arn
  spamBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 's3:PutObject'
            Sid: AllowSESPuts
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref emailBucket
                - /*
            Effect: Allow
            Principal: '*'
      Bucket: !Ref emailBucket
  receiptRule:
    Type: 'AWS::SES::ReceiptRule'
    Properties:
      Rule:
        Name: spam
        Actions:
          - S3Action:
              BucketName: !Ref emailBucket
        Enabled: true
      RuleSetName: default-rule-set
