AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Spam Filtering
Parameters:
  SageMakerEndpointName:
    Type: String
    Default: "sms-spam-classifier-mxnet-2021-04-01-03-00-09-451"
  S3BucketName:
    Type: String
    Default: email-bucket-v2
Resources:
  spamFilter:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: spam-filter
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./spam-filter
      Description: "Lambda function for Spam Filter"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::269578278636:role/admin-lambda-role"
      Environment:
        Variables:
          REGION: us-east-1
          ENDPOINT:
            Ref: SageMakerEndpointName
  BucketPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: 
        Fn::GetAtt:
          - spamFilter
          - Arn
      Principal: s3.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn:
        Fn::Sub: arn:aws:s3:::${S3BucketName}
  S3EmailBucket:
    Type: AWS::S3::Bucket
    DependsOn: BucketPermission
    Properties:
      BucketName: !Ref S3BucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:Put'
            Function: !GetAtt 
              - spamFilter
              - Arn      
  spamBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 's3:PutObject'
            Sid: AllowSESPuts
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3EmailBucket
                - /*
            Effect: Allow
            Principal: '*'
      Bucket: !Ref S3EmailBucket
  receiptRule:
    Type: 'AWS::SES::ReceiptRule'
    Properties:
      Rule:
        Name: spam
        Actions:
          - S3Action:
              BucketName: !Ref S3EmailBucket
        Enabled: true
      RuleSetName: default-rule-set